// Building catalogue. Each type defines its economics and 3D appearance.
// income is dollars/second; pop is population added; tier gates unlock by
// total buildings placed so the player progresses through the list.

export const BUILDINGS = {
  house: {
    name: "House",
    icon: "🏠",
    cost: 100,
    income: 1,
    pop: 4,
    tier: 0,
    color: 0x8ecae6,
    roof: 0xef6f6c,
    height: 0.9,
    desc: "Cozy starter home",
  },
  shop: {
    name: "Corner Shop",
    icon: "🏪",
    cost: 600,
    income: 7,
    pop: 2,
    tier: 3,
    color: 0xffd166,
    roof: 0xe76f51,
    height: 1.1,
    desc: "Sells the essentials",
  },
  cafe: {
    name: "Café",
    icon: "☕",
    cost: 2000,
    income: 24,
    pop: 3,
    tier: 8,
    color: 0xb08968,
    roof: 0x6f4518,
    height: 1.3,
    desc: "Caffeine = profit",
  },
  factory: {
    name: "Factory",
    icon: "🏭",
    cost: 7500,
    income: 90,
    pop: 12,
    tier: 14,
    color: 0x9aa0a6,
    roof: 0x5f6368,
    height: 1.6,
    desc: "Industrial output",
  },
  office: {
    name: "Office Block",
    icon: "🏢",
    cost: 28000,
    income: 320,
    pop: 40,
    tier: 22,
    color: 0x4895ef,
    roof: 0x3a0ca3,
    height: 2.8,
    desc: "White-collar money",
  },
  hotel: {
    name: "Grand Hotel",
    icon: "🏨",
    cost: 110000,
    income: 1200,
    pop: 80,
    tier: 32,
    color: 0xf4a261,
    roof: 0x9d0208,
    height: 3.4,
    desc: "Luxury stays pay well",
  },
  tower: {
    name: "Skyscraper",
    icon: "🏙️",
    cost: 450000,
    income: 5000,
    pop: 250,
    tier: 45,
    color: 0x90e0ef,
    roof: 0x023e8a,
    height: 5.2,
    desc: "Reach for the sky",
  },
  arcology: {
    name: "Arcology",
    icon: "🌆",
    cost: 2000000,
    income: 24000,
    pop: 1000,
    tier: 60,
    color: 0xc77dff,
    roof: 0x3c096c,
    height: 6.6,
    desc: "A city within a building",
  },
};

export const BUILDING_KEYS = Object.keys(BUILDINGS);
